services:
  db:
    image: postgres:16-alpine
    container_name: order-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: order-api-app
    environment:
      DSN: "host=db user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"
      TOKEN: "dev-only-change-me-9f3a1c7e5b2d4680aa11bb22cc33dd44"
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
